services:
  frontend:
    build: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend/src/:/app/src
      - ./frontend/codegen.ts/:/app/codegen.ts
      - ./frontend/.env:/app/.env
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend/src/:/app/src
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend:3000'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}

  database:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - ./database:/var/lib/postgresql/data
