services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src/:/app/src/
      - ./frontend/codegen.ts:/app/codegen.ts
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --request GET --url 'http://frontend-dev:5173' || exit 1",
        ]
    depends_on:
      backend-dev:
        condition: service_healthy

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src/:/app/src/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend-dev:3000'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    depends_on:
      database-dev:
        condition: service_healthy

    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      API_PORT: ${API_PORT}

  database-dev:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - ./database:/var/lib/postgresql

  gateway-dev:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      backend-dev:
        condition: service_healthy
      frontend-dev:
        condition: service_healthy

  adminer-dev:
    image: adminer
    depends_on:
      database-dev:
        condition: service_healthy
