FROM node:lts-alpine AS frontend-builder
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci
COPY ./frontend/ ./
RUN ["npm", "run", "build"]

FROM nginx:stable-alpine
COPY ./gateway/nginx.prod.conf /etc/nginx/nginx.conf
COPY --from=frontend-builder /app/dist /usr/share/nginx/html
CMD ["nginx","-g","daemon off;"]
