FROM node:lts-alpine AS frontend-builder
ARG VITE_API_URL_FROM_CLIENT
ARG VITE_CLOUNDINARY_CLOUD_NAME
ARG VITE_CLOUNDINARY_UPLOAD_PRESET

WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci
COPY ./frontend/ ./
RUN ["npm", "run", "build"]

FROM nginx:stable-alpine
COPY gateway/nginx.prod.conf /etc/nginx/templates/default.conf.template
COPY --from=frontend-builder /app/dist /usr/share/nginx/html
