FROM node:lts-alpine AS builder
WORKDIR /app
COPY *.json .
RUN npm i
RUN npm i -g typescript
COPY src/ .
RUN ["npm", "run", "build"]

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/build ./build
COPY package*.json .
RUN apk --no-cache add curl
RUN npm i --production

CMD ["npm", "run", "start"]
