FROM node:lts-alpine AS backend-builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src/ ./src
RUN npm run build

FROM node:lts-alpine
RUN apk --no-cache add --no-scripts curl
WORKDIR /app
COPY --from=backend-builder /app/package*.json ./
RUN npm ci --only=production
COPY --from=backend-builder /app/dist ./dist

CMD ["node", "dist/index.js"]
